<a href="https://colab.research.google.com/github/Arsenii-S7/stepik-DS-ML/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🤖 Тема 1.8: Практические задания (Pandas)

In [13]:
# Задание 1
# Любым удобным для вас способом создайте dataframe c именем my_data, в котором
# две колонки c именами (type - строки, value - целые числа) и четыре наблюдения в каждой колонке:

import pandas as pd

my_data = pd.DataFrame({
    'type': ['A', 'A', 'B', 'B'],
    'value': [10, 14, 12, 23]
})
my_data.head(5)

  type  value
0    A     10
1    A     14
2    B     12
3    B     23

In [11]:
import pandas as pd
import io

df = '''
type value
A 10

A 14

B 12

B 23
'''
my_data = pd.read_csv(io.StringIO(df), sep=' ')
my_data.head(5)

  type  value
0    A     10
1    A     14
2    B     12
3    B     23

In [18]:
# Особенно важный навык при работе с данными - это умение быстро и эффективно отбирать нужные вам колонки или строки.

# Начнем с простого, в dataframe с именем my_stat сохранено 20 строк и четыре колонки (V1, V2, V3, V4):

# В переменную с именем subset_1 сохраните только первые 10 строк и только 1 и 3 колонку.
# В переменную с именем subset_2 сохраните все строки кроме 1 и 5 и только 2 и 4 колонку.

# Помните, что нумерация индексов строк и колонок начинается с 0.

# Обратите внимание, получившиеся subset_1 и subset_2 - тоже должны быть dataframe.


stats = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat.csv')
stats.head(5)


subset_1 = stats.loc[:9, ['V1', 'V3']]   # первые 10 строк (индексы 0..9)
# print(subset_1)
subset_2 = stats.drop(index=[0,4]).loc[:, ['V2', 'V4']]
# print(subset_2)

       V2   V4
1     7.0  1.0
2    11.0  0.0
3    11.0  2.0
5    11.0  0.0
6     9.0  2.0
..    ...  ...
495   8.0 -1.0
496   8.0  1.0
497  11.0  2.0
498  11.0  2.0
499   8.0  1.0

[498 rows x 2 columns]

In [21]:
# Теперь потренируемся отбирать нужные нам наблюдения (строки), соответствующие некому условию. В dataframe с именем my_stat четыре колонки V1, V2, V3, V4:

# В переменную subset_1 сохраните только те наблюдения, у которых значения переменной V1  строго больше 0, и значение переменной V3  равняется 'A'.

# В переменную  subset_2  сохраните только те наблюдения, у которых значения переменной V2  не равняются 10, или значения переменной V4 больше или равно 1.


subset_1 = stats[(stats['V1'] > 0) & (stats['V3'] == 'A')]
subset_2 = stats[(stats['V2'] != 10) | (stats['V4'] >= 1)]

     V1    V2 V3   V4
0     2  13.0  B  1.0
1    -1   7.0  B  1.0
2     0  11.0  A  0.0
3     2  11.0  A  2.0
5     2  11.0  A  0.0
..   ..   ... ..  ...
495   1   8.0  A -1.0
496   3   8.0  A  1.0
497  -1  11.0  B  2.0
498   1  11.0  A  2.0
499   0   8.0  B  1.0

[447 rows x 4 columns]

In [22]:
import pandas as pd
subset_1 = stats.loc[(stats.V1 > 0) & (stats.V3 == 'A')]
subset_2 = stats.query("V2!=10 | V4 >=1")

In [26]:
import pandas as pd
import numpy as np

# Теперь давайте преобразуем наши данные. В переменной my_stat лежат данные с которыми вам необходимо проделать следующее дейтвие.
# В этих данных (my_stat) создайте две новые переменных:


my_stat = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat.csv')

my_stat['V5'] = my_stat.V1 + my_stat.V4
my_stat = my_stat.assign(V6 = np.log(my_stat.V2))
# my_stat.head()

   V1    V2 V3   V4   V5        V6
0   2  13.0  B  1.0  3.0  2.564949
1  -1   7.0  B  1.0  0.0  1.945910
2   0  11.0  A  0.0  0.0  2.397895
3   2  11.0  A  2.0  4.0  2.397895
4   0  10.0  B -1.0 -1.0  2.302585

In [28]:
# Переименуйте колонки в данных  my_stat следующим образом:

# V1 -> session_value

# V2 -> group

# V3 -> time

# V4 -> n_users


my_stat = my_stat.rename(columns={'V1': 'session_value', 'V2': 'group', 'V3': 'time', 'V4': 'n_users'})
my_stat.head()

   session_value  group time  n_users   V5        V6
0              2   13.0    B      1.0  3.0  2.564949
1             -1    7.0    B      1.0  0.0  1.945910
2              0   11.0    A      0.0  0.0  2.397895
3              2   11.0    A      2.0  4.0  2.397895
4              0   10.0    B     -1.0 -1.0  2.302585

In [33]:
# давайте разберемся, как заменять наблюдения в данных.

# В dataframe с именем my_stat сохранены данные с 4 колонками: session_value, group, time, n_users.

# В переменной session_value замените все пропущенные значения на нули.

# В переменной n_users замените все отрицательные значения на медианное значение переменной n_users (без учета отрицательных значений, разумеется).

# Как получить медиану переменной n_users без учета отрицательных значений? Если не придумали решения, подсказка - ищите один из возможных ответов в задачах, которые мы уже решили.

# Данные для тренировки.


my_stat1 = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat_1.csv')
my_stat = my_stat1 .copy()


# Метод fillna()
# Этот метод используется для замены значений NaN (пропусков)
my_stat['session_value'] = my_stat['session_value'].fillna(0)

# Создаём маску для неотрицательных значений n_users
non_neg_mask = my_stat['n_users'] >= 0

# Вычисляем медиану n_users только по неотрицательным значениям
median_n_users = my_stat.loc[non_neg_mask, 'n_users'].median()

# Заменяем отрицательные значения на медиану
my_stat['n_users'] = my_stat['n_users'].apply(lambda x: x if x >= 0 else median_n_users)

# Или альтернатива без apply (быстрее):
# my_stat.loc[~non_neg_mask, 'n_users'] = median_n_users

my_stat.head(10)

   session_value  time group  n_users
0            0.0    12     B      9.0
1            0.0    11     A      5.0
2            1.0     8     A      1.0
3            2.0     9     B      3.0
4            2.0    10     B      9.0
5            3.0     8     A      8.0
6            0.0    11     B      5.0
7            0.0     9     A      4.0
8            0.0     8     B      5.0
9            0.0     9     A      5.0

In [39]:
# В этой задаче для данных my_stat рассчитайте среднее значение переменной session_value
# для каждой группы (переменная group), в получившемся dataframe  переменная group
# не должна превратиться в индекс. Также переименуйте колонку со средним значением session_value в mean_session_value.

# Получившийся результат сохраните в dataframe с именем mean_session_value_data.


my_stat1 = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat_1.csv')



mean_session_value_data = my_stat1.groupby('group', as_index=False).aggregate({'session_value': 'mean'})
mean_session_value_data = mean_session_value_data.rename(columns={'session_value': 'mean_session_value'})

  group  mean_session_value
0     A                 1.0
1     B                 1.0